'use client';
import {useRef,useState} from 'react';
import {Upload,ArrowRight,FileText,ShieldCheck,Zap} from 'lucide-react';
import {useRouter} from 'next/navigation';

export default function Home(){
 const input=useRef<HTMLInputElement>(null); const router=useRouter(); const [busy,setBusy]=useState(false); const [err,setErr]=useState('');
 const run=async(file:File)=>{setBusy(true);setErr('');try{const fd=new FormData();fd.append('file',file);const r=await fetch(`${process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000'}/v1/reconstruct`,{method:'POST',body:fd});if(!r.ok)throw new Error(await r.text());const result=await r.json();sessionStorage.setItem('aedom',JSON.stringify(result.document));router.push('/editor')}catch(e){setErr(e instanceof Error?e.message:'Upload failed')}finally{setBusy(false)}};
 return <main className="min-h-screen"><nav className="flex items-center justify-between px-8 py-5 bg-white border-b"><div className="flex items-center gap-3 font-bold text-lg"><div className="w-9 h-9 rounded-xl bg-black text-white grid place-items-center">AE</div>Anything Editable</div><a className="text-sm text-slate-600 hover:text-black" href="/editor">Open editor</a></nav><section className="max-w-6xl mx-auto px-6 py-20"><div className="max-w-3xl"><div className="inline-flex gap-2 items-center px-3 py-1 rounded-full bg-slate-100 text-sm"><Zap size={15}/> Document reconstruction, not OCR</div><h1 className="text-6xl font-black tracking-tight mt-6 leading-tight">Anything you can see.<br/><span className="text-slate-500">Anything you can edit.</span></h1><p className="text-xl text-slate-600 mt-6 max-w-2xl">Upload a PDF, screenshot, invoice, resume or image. Reconstruct the structure into real editable text, shapes and objects, then export it.</p></div><div className="mt-12 border-2 border-dashed border-slate-300 bg-white rounded-3xl p-10 flex flex-col items-center text-center shadow-sm"><div className="w-16 h-16 rounded-2xl bg-slate-100 grid place-items-center"><Upload/></div><h2 className="text-2xl font-bold mt-5">Make a document editable</h2><p className="text-slate-500 mt-2">PDF, PNG, JPG, WEBP up to 25 MB</p><button disabled={busy} onClick={()=>input.current?.click()} className="mt-6 px-6 py-3 rounded-xl bg-black text-white font-semibold disabled:opacity-50">{busy?'Reconstructing…':'Choose file'}</button><input ref={input} hidden type="file" accept=".pdf,.png,.jpg,.jpeg,.webp" onChange={e=>e.target.files?.[0]&&run(e.target.files[0])}/>{err&&<p className="text-red-600 text-sm mt-4">{err}</p>}</div><div className="grid md:grid-cols-3 gap-5 mt-8"><Feature icon={<FileText/>} title="Real elements" text="Text, tables, images, shapes and backgrounds stay individually editable."/><Feature icon={<ShieldCheck/>} title="Confidence-aware" text="Low-confidence regions are flagged instead of silently pretending they are perfect."/><Feature icon={<ArrowRight/>} title="Export anywhere" text="Export the reconstructed AEDOM to PDF, DOCX, HTML or SVG."/></div></section></main>}
function Feature({icon,title,text}:{icon:React.ReactNode,title:string,text:string}){return <div className="bg-white rounded-2xl p-6 border"><div className="w-10 h-10 rounded-xl bg-slate-100 grid place-items-center">{icon}</div><h3 className="font-bold mt-4">{title}</h3><p className="text-sm text-slate-500 mt-2 leading-6">{text}</p></div>}
